### ISSUE TITLE
scaler.pkl expects 15 features as input while the other models are trained on 16

### ISSUE THREAD

**Issue by remcova** [KyujinHan/Object-Depth-detection-based-hybrid-Distance-estimator#2]
The provided standard_scaler.pkl file expects 15 features while the input in ODD_application_LSTM.py is giving 16.
Also the lstm.py expects 16 features.

Can you guys provide the correct standard_scaler.pkl file so we can run the demo? would be appreciated :)

**Comment by KyujinHan** [comment]
Hello! Thanks for your intereset our project!

We updated the correct .pkl file on the model performance table.
Sorry for the confusion..^^

Thanks!

**Comment by remcova** [comment]
Thank you! :)
